version: '3.8'

services:
  api:
    build:
      context: ./server
    depends_on:
      - db
    volumes:
      - ./config/conf.yaml:/etc/incrowd-api/conf.yaml
    entrypoint: /incrowd-api
    command: -config=/etc/incrowd-api/conf.yaml
    environment:
      DEFAULT_API_CONFIG_PATH: ${DEFAULT_API_CONFIG_PATH}
    ports:
      - 8083:8083

  db:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./db/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
      - ./db/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
